### ISSUE TITLE
Filter logs

### ISSUE THREAD

**Issue by jjfalling** [elastic/elasticsearch-support-diagnostics#1]
As originally requested by  @dadoonet :

May be we don't need to have 30 days of log files (depending on their logging settings).
Could it be possible to specify something like --days 1 to get only the last day of logs or so?

I think our default log4j settings do daily rollovers, so this certainly seems possible.

**Comment by robin13** [comment]
Precurser: https://github.com/elastic/elasticsearch-support-diagnostics/issues/70

**Comment by jjfalling** [comment]
looks like we added this in 2.x with a --archivedLogs flag.
