### ISSUE TITLE
File type not set correctly. Set to .gz should be .bz2

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch-support-diagnostics#103]
Just received two diags (created with 2.0.7) that had `.tar.gz` as file type but were actually compressed with `bzip2`, so they should use `.bz2` as file type.

```
# file *.gz
diagnostics-20160420-143930.tar.gz: bzip2 compressed data, block size = 900k
diagnostics-20160420-150249.tar.gz: bzip2 compressed data, block size = 900k
```
Probably caused by https://github.com/elastic/elasticsearch-support-diagnostics/commit/5dcc54f5d61a769f013b30db0547cf5dbce2155e

**Comment by nemonster** [comment]
Fixed and redeployed.  Sorry about that!

**Comment by jakommo** [comment]
:+1:
