### ISSUE TITLE
Use ?human for index settings

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-support-diagnostics#105]
When getting index settings, let's add ?human to the request.  Use case [here](https://github.com/elastic/elasticsearch/issues/17862)

**Comment by nemonster** [comment]
@jjfalling @robin13 This break anything?

**Comment by robin13** [comment]
Just adds (useful) data, not changing data structure, so all good from my side! :)

**Comment by nemonster** [comment]
Will be in the next release.
