### ISSUE TITLE
Capture templates

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#107]
Would it be possible to also capture the templates

```
GET /_template
```

**Comment by GlenRSmith** [comment]
👍 
Yes, they are in the cluster state, but so are other things that we capture. When you have a large cluster state, it can be a pain to extract selected items, and working with peoples' templates is something we have to do quite frequently.

**Comment by nemonster** [comment]
Don't disagree.  It will be in the next version, out in the next couple of days.
