### ISSUE TITLE
When anon access is enabled in shield, diag does not use provided user

### ISSUE THREAD

**Issue by jjfalling** [elastic/elasticsearch-support-diagnostics#109]
When anon access is enabled in shield the output from the diag shows that the anon user is being used instead of the the one provided by the --user flag.  

Tested on ES 2.3 and the latest diag.

**Comment by nemonster** [comment]
Can't fix.  Doesn't have anything to do with the diagnostic utility.  It's a Shield issue.  I just ran the following test, using both a browser and GraphicalHttpClient, a curl like GUI.  Steps to reproduce:

* Create an admin user, such as esadmin/esadmin.
* Run _cat/nodes and/or _cat/indices to verify it works.
* Add the following to the configuration and restart the server:
```
shield.authc.anonymous.roles: user
shield.authc.anonymous.username: _es_anonymous_user
shield.authc.anonymous..authz_exception: true
```
* Run http://localhost:9200 to get version information. Runs fine.
* Test it with _cat/indices and an authorization error occurs.
* Run the version query with the esadmin:esadmin account. Should work.
* Run the same thing with the _cat/nodes or _cat/indices. Should get an authorization error.
```
{
    "status": 403,
    "error": {
        "root_cause": [
            {
                "type": "security_exception",
                "reason": "action [cluster:monitor/state] is unauthorized for user [_es_anonymous_user]"
            }
        ],
        "type": "security_exception",
        "reason": "action [cluster:monitor/state] is unauthorized for user [_es_anonymous_user]"
    }
}
```
Copied the between tests just to make sure it remained consistent.

http://esadmin:esadmin@localhost:9200/_cat/nodes

Have submitted it as an issue to the Shield repo.  But for now it would appear that if you're using anonymous access it isn't going to work from any REST based interface.

**Comment by nemonster** [comment]
It appears that shield.authc.anonymous.authz_exception: false is necessary to allow the elevated access.  I just tried this and it's working for me with that setting.
