### ISSUE TITLE
Diagnostic tool or _cat API needs to be modified in order to ignore unavailable indices in an alias

### ISSUE THREAD

**Issue by evanv** [elastic/elasticsearch-support-diagnostics#110]
The diagnostic tool breaks when you have aliases that point at closed indices. Per the decision to keep the default behavior and use workarounds (eg https://github.com/elastic/elasticsearch/issues/14982#issuecomment-165981661 and https://github.com/elastic/elasticsearch/issues/15730#issuecomment-171260579), it seems like the diagnostic tool needs to pass an additional parameter to ignore unavailable (if that is possible) or the _cat API needs to have an option to ignore unavailable.... or both. 

to replicate on your end, create an alias that points at a handful of indices. Close one of them. Don't update the alias. Then run the diagnostic tool. You'll see a lot of this kind of thing. 

```
Trying REST Endpoint.
Currently running the following query:alias
Diagnostic query: alias was retrieved and saved to disk.
Currently running the following query:allocation
Diagnostic query: allocation was retrieved and saved to disk.
Currently running the following query:cat_master
Diagnostic query: cat_master was retrieved and saved to disk.
Currently running the following query:cat_nodes
Diagnostic query: cat_nodes was retrieved and saved to disk.
Currently running the following query:cat_indices
Diagnostic query: cat_indices was retrieved and saved to disk.
Currently running the following query:cat_count
cat_count query returned: 403/Forbidden
Diagnostic query: cat_count was retrieved and saved to disk.
Currently running the following query:cat_segments
cat_segments query returned: 403/Forbidden
Diagnostic query: cat_segments was retrieved and saved to disk.
Currently running the following query:cat_health
Diagnostic query: cat_health was retrieved and saved to disk.
Currently running the following query:cat_pending_tasks
Diagnostic query: cat_pending_tasks was retrieved and saved to disk.
Currently running the following query:cat_aliases
Diagnostic query: cat_aliases was retrieved and saved to disk.
Currently running the following query:cat_thread_pool
Diagnostic query: cat_thread_pool was retrieved and saved to disk.
Currently running the following query:cat_fielddata
Diagnostic query: cat_fielddata was retrieved and saved to disk.
Currently running the following query:cat_shards
cat_shards query returned: 403/Forbidden
Diagnostic query: cat_shards was retrieved and saved to disk.
Currently running the following query:cluster_health
Diagnostic query: cluster_health was retrieved and saved to disk.
Currently running the following query:cluster_pending_tasks
Diagnostic query: cluster_pending_tasks was retrieved and saved to disk.
Currently running the following query:cluster_settings
Diagnostic query: cluster_settings was retrieved and saved to disk.
Currently running the following query:cluster_state
Diagnostic query: cluster_state was retrieved and saved to disk.
Currently running the following query:cluster_stats
Diagnostic query: cluster_stats was retrieved and saved to disk.
Currently running the following query:count
count query returned: 403/Forbidden
Diagnostic query: count was retrieved and saved to disk.
Currently running the following query:indices_stats
indices_stats query returned: 403/Forbidden
Diagnostic query: indices_stats was retrieved and saved to disk.
Currently running the following query:licenses
Diagnostic query: licenses was retrieved and saved to disk.
Currently running the following query:mapping
Diagnostic query: mapping was retrieved and saved to disk.
Currently running the following query:nodes_hot_threads
Diagnostic query: nodes_hot_threads was retrieved and saved to disk.
Currently running the following query:nodes_stats
Diagnostic query: nodes_stats was retrieved and saved to disk.
Currently running the following query:fielddata_stats
Diagnostic query: fielddata_stats was retrieved and saved to disk.
Currently running the following query:plugins
Diagnostic query: plugins was retrieved and saved to disk.
Currently running the following query:cat_recovery
cat_recovery query returned: 403/Forbidden
Diagnostic query: cat_recovery was retrieved and saved to disk.
Currently running the following query:recovery
recovery query returned: 403/Forbidden
Diagnostic query: recovery was retrieved and saved to disk.
Currently running the following query:shards
shards query returned: 403/Forbidden
Diagnostic query: shards was retrieved and saved to disk.
Currently running the following query:segments
segments query returned: 403/Forbidden
```

**Comment by nemonster** [comment]
> to replicate on your end, create an alias that points at a handful of indices. Close one of them. Don't update the alias. Then run the diagnostic tool. You'll see a lot of this kind of thing.

I'm not seeing this and I did exactly that. At least as closely as I could with the information provided.  I can investigate further but I'll need a bit more info.

* Please specify the Elasticsearch version and the diag version.  
* Was Shield was installed?
* If so, what level of authority was the user account used for the diagnostic assigned?
* Was anonymous access also enabled (there are some possible issues here).
* Feel free to attach a script that replicates exactly with a small amount of test data.  It will expedite things since I don't see the same behavior.

**Comment by evanv** [comment]
> Was Shield was installed?

Yes

> If so,  what level of authority was the user account used for the diagnostic assigned?

Admin

> Was anonymous access also enabled (there are some possible issues here).

No

>Feel free to attach a script that replicates exactly with a small amount of test data. It will expedite things since I don't see the same behavior.   

At a conference this weekend but I'll get back to you with that.

**Comment by evanv** [comment]
Just tested this on ES 2.2 without Shield and I'm not seeing any issues either. Next week, I'll double check and make sure I wasn't doing anything stupid and, if nothing obviously is, I'll put together a script to replicate this. If this is a false alarm, I apologize in advance.... but I won't be able to dig in further until I get back next week
