### ISSUE TITLE
Capture "nodes.xyz.jvm.using_compressed_ordinary_object_pointers" from /_nodes in >= ES 2.2

### ISSUE THREAD

**Issue by bczifra** [elastic/elasticsearch-support-diagnostics#120]
We should capture nodes.xyz.jvm.using_compressed_ordinary_object_pointers: true/false in >= ES 2.2 to have definitive proof that ES is using compressed OOPS.

**Comment by nemonster** [comment]
Not sure I understand.  It's in the nodes output already, so I'm unsure of what else needs to be done?
