### ISSUE TITLE
Cant run diagnostics.sh cant find .java file

### ISSUE THREAD

**Issue by brianbola** [elastic/elasticsearch-support-diagnostics#122]
./diagnostics.sh --host X.X.X.X -u -p
Using /usr/java/jre1.8.0_91/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Error: Could not find or load main class com.elastic.support.diagnostics.DiagnosticApp

**Comment by nemonster** [comment]
That's generally the result of downloading the source archive rather than the dist zip and trying to run an uncompiled distribution.

**Comment by brianbola** [comment]
Apologies My Mistake
