### ISSUE TITLE
Get important sysctl settings on Linux

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch-support-diagnostics#126]
On Linux, it might be useful to get some of the important sysctl settings we recommend people check.  It should be sufficient to just call `sysctl <name-of-setting>` to grab these, else just `sysctl -a` to grab all settings (might be less useful, there are a lot we don't care about).

* vm.max_map_count
* vm.dirty_ratio
* vm.dirty_background_ratio
* net.core.somaxconn
* fs.file-max

Any others?

**Comment by msimos** [comment]
Probably just grab sysctl -a.

**Comment by nemonster** [comment]
Done, just haven't pushed yet.  Next release.
