### ISSUE TITLE
Parse log files in diagnostics archive for deprecation messages

### ISSUE THREAD

**Issue by bczifra** [elastic/elasticsearch-support-diagnostics#130]
It would be nice to have the tool parse any included log files for deprecation messages and add a tab for them.

**Comment by joshuar** [comment]
Would having a tab of the deprecation log be suitable?

**Comment by nemonster** [comment]
I think you're talking about the stats tool. All this does is run the REST Api and collect the logs and configs.  No tabs involved.

**Comment by jjfalling** [comment]
Closing as this is opened under the wrong repo.
