### ISSUE TITLE
[5.0] "output_uuid=true" param was removed from _cluster/stats 

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch-support-diagnostics#132]
The `output_uuid=true` param was removed from _cluster/stats in 5.0 and with the new strict param check, this results in an exception. https://github.com/elastic/elasticsearch/pull/21020
The cluster uuid is now included in `/?` which we already capture. https://github.com/elastic/elasticsearch/pull/20503

Currently:

```
% curl '10.148.200.137:9200/_cluster/stats?pretty&human&output_uuid=true'                                                                         
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "request [/_cluster/stats] contains unrecognized parameter: [output_uuid]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "request [/_cluster/stats] contains unrecognized parameter: [output_uuid]"
  },
  "status" : 400
}
```

Dropping `&output_uuid=true` solves the issue. I tested by removing this from the command in the `diag.yml` but we need to find a way to keep it in 1.x and 2.x and drop it in 5.x

**Comment by nemonster** [comment]
Fixed.
