### ISSUE TITLE
[5.0] _nodes?all results in exception

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch-support-diagnostics#133]
The `/_nodes?all&pretty&human` results in an exception as the is no `?all` param.
Caused by https://github.com/elastic/elasticsearch/pull/20722.

E.g.:

```
% curl '10.148.200.137:9200/_nodes?all&pretty&human'                     
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "request [/_nodes] contains unrecognized parameter: [all]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "request [/_nodes] contains unrecognized parameter: [all]"
  },
  "status" : 400
}
```

After discussion with dev, there was never an `all` param on this API. I removed it on `2.4` and compared the output and it was identical to the one including `all`, so this does nothing anyways.
Suggest to remove it from all versions.

**Comment by nemonster** [comment]
Fixed but not deployed yet.
