### ISSUE TITLE
make elasticsearch config path configurable

### ISSUE THREAD

**Issue by LucaWintergerst** [elastic/elasticsearch-support-diagnostics#136]
Got the following exception today while attempting to run a diag in a docker container:

java.io.FileNotFoundException: Source '/usr/share/elasticsearch/config' does not exist

They have their config in a custom directory 

Keep in mind that this could also be a docker problem only

**Comment by nemonster** [comment]
Docker problem more than likely.  Check the nodes.json settings.  If there's a config directory set it will look for the config file there. So the question would be what it will get when it tries to access that directory. 

Note, per the instructions you can run it with 
--type remote 

to bypass copying and scrubbing the config and the logs.  

Also curious where you are running the diagnostic from?  That may have an impact as well.

**Comment by LucaWintergerst** [comment]
Saw your comment too late. 
This makes sense. I will try to verify with the customer
