### ISSUE TITLE
On Linux check CPU frequency governor

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch-support-diagnostics#137]
On Linux systems, we should probably check the CPU frequency governor, just in case it is set to something like `powersave`.  

**If we can confirm that the various Linux distributions we support do not enable CPU frequency scaling on their server versions, we might be okay.  However we don't make the distinction of server vs desktop version.**  

It's easiest to just check or capture the contents of the file `/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`.  If this file doesn't exist, then no CPU frequency scaling is active.  If it does exist, a support agent can check the contents to ensure it is not `powersave`.

**Comment by nemonster** [comment]
I'm assuming this requires elevated privileges though, right? That's actually becoming an issue, since a lot of things system wise often fail because the person running doesn't have the proper permissions. And will the above work across distributions?

**Comment by nemonster** [comment]
Added for next release.
