### ISSUE TITLE
Don't grab the *_access.log*'s by default

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch-support-diagnostics#139]
By default, the diag also collects the `*_access.log*` logs from the node running on. 
While this can be useful in a few cases, it unnecessarily blows up the archive size.

I'd like to propose to not grab these by default and rather have an param `--include-access-log` (or something) to only grab them when explicitly requested.

Not sure how others feel about this?

**Comment by jpcarey** [comment]
+1 I had a 6gb access log in a diagnostic not too far back. Certainly slows down the download. If we want to leave it on by default, maybe run `grep -v > trimmed_file` to remove authorized entries. Maybe even limit to the last 10k lines?

**Comment by nemonster** [comment]
This has been requested unofficially a few times and it was easy to do so I've implemented it in the manner suggested. By default it will skip them but you can enable collection via the --accessLogs flag. It's kind of a pain to parse individual files and it would take a larger scale refactoring of that routine so I'm going to hold off on that suggestion for a while.

**Comment by joshuar** [comment]
This seems like solving the wrong problem?  These files should compress
really well?  The real problem here is that downloading from Salesforce is
too slow?

**Comment by jakommo** [comment]
Well, the slow download is a problem as well, but even with good compression it's a difference between a diag being `<1MB` or `>20MB`. 
It also wastes a lot of disk space, I had once a access log that was almost 20GB after extracting.

**Comment by jakommo** [comment]
Closed by https://github.com/elastic/elasticsearch-support-diagnostics/commit/48b0e3275b9be8f84e10ac8450d3282082da05a9
