### ISSUE TITLE
Replace spaces in filename/path to become more shell friendly 

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch-support-diagnostics#140]
Currently the config and logs are captured in a dir called `NODENAME-log and config`.
I would appreciate not having any spaces in path and filenames, as they need to be escaped in a shell.
E.g. if I run a find on multiple diags, I can't just copy and paste the path as it includes a space, which i need to escape first. 

Can we replace the space by `_` ?

**Comment by nemonster** [comment]
Done - will be in 1/24 release.
