### ISSUE TITLE
duplicated node settings / logs

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch-support-diagnostics#141]
I am seeing an issue where the diagnostic collects data for what looks like two nodes, but only a single node is running (and the data is duplicated).

```
{
  "diagToolVersion" : "2.0.7",
  "clusterName" : "<removed>",
  "diagNode" : "",
  "host" : "<removed>ela03m<removed>",
  "collectionDate" : "2017-01-13T15:53:12.170+0000"
}
```
Two nodes from file view:
![duplicate_node](https://cloud.githubusercontent.com/assets/5118470/21937596/2d0ec130-d975-11e6-90df-988c0063780f.png)

Folder diff (recursive file content) shows no difference between the two nodes:
![folder_compare](https://cloud.githubusercontent.com/assets/5118470/21937605/34192f2e-d975-11e6-825b-429cde5ab6dd.png)

**Comment by nemonster** [comment]
This should be addressed in the upcoming release.
