### ISSUE TITLE
manifest.json contain password

### ISSUE THREAD

**Issue by flysen** [elastic/elasticsearch-support-diagnostics#143]
Don't think manifest.json sould contain password in clear text.

**Comment by nemonster** [comment]
Hmm, what version are you running? That shouldn't be an issue in the latest.

**Comment by flysen** [comment]
https://github.com/elastic/elasticsearch-support-diagnostics/releases/download/5.4/support-diagnostics-5.4-dist.zip

**Comment by nemonster** [comment]
There's a 5.5 version out where that's fixed.

**Comment by flysen** [comment]
Thanks, I've missed that.
Cheers Fredrik
