### ISSUE TITLE
Scrubbing error

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch-support-diagnostics#148]
@nemonster mind taking a look at this?

We are getting the following:

```
Error scrubbing log and config files.
java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0*_log_config
```

Here are the complete logs: 

[diagnotics.txt](https://github.com/elastic/elasticsearch-support-diagnostics/files/913065/diagnotics.txt)

Is it because the pattern is incorrect?

**Comment by nemonster** [comment]
Fixed in 5.12
