### ISSUE TITLE
Remove "spins" flag from diagnostics

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch-support-diagnostics#149]
We're removing the `spins` flag from the node stats API in 6.0 (see https://github.com/elastic/elasticsearch/issues/24390) and I think you include this flag in visualizations so I just wanted to give you a heads-up so the support tools don't break.

**Comment by nemonster** [comment]
@danielmitterdorfer Thanks. It's not currently used, but I had considered including it so thanks for the heads up.

**Comment by danielmitterdorfer** [comment]
You're welcome. I think we can then close the issue again @nemonster?

**Comment by nemonster** [comment]
@danielmitterdorfer Absolutely. Got sidetracked for bugpool. Closing now.
