### ISSUE TITLE
_cat/nodes disk usage

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch-support-diagnostics#159]
_cat/nodes will provide disk usage, based upon this PR: https://github.com/elastic/elasticsearch/pull/21775

We customized the columns, to include the node id. Need to investigate if the disk column can be added (which is likely on by default in newer releases) without causing an error for versions of elasticsearch that would not support this.

**Comment by nemonster** [comment]
Added for the new 6.0 calls. Not sure what to do about the 5.6 since I usually stay on major version. I'll test it to see if it breaks a 5.5 and if not I'll put it in there as well.

**Comment by nemonster** [comment]
Works as far back as 5.1.1 so adding to the 5 output. Sorry this one took so long...
