### ISSUE TITLE
Add Check For Transparent Huge Pages 

### ISSUE THREAD

**Issue by MorrieAtElastic** [elastic/elasticsearch-support-diagnostics#170]
Please add a check to see that Transparent Huge Pages is disabled on any Linux server running Elasticsearch executables. 

To the best of my understanding, the check for THP status is global for all variants of linux: 

```
cat /sys/kernel/mm/transparent_hugepage/enabled 
```

Acceptable values are “never” or “madvise”; a value of “always” should result in a warning being issued by the Support Diagnostic utility. 

Check https://techoverflow.net/2013/08/01/checking-if-hugepages-are-enabled-in-linux/ for more information.

**Comment by nemonster** [comment]
Added.
