### ISSUE TITLE
Use dmesg with "-T" option to get real timestamps instead of mills since startup 

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch-support-diagnostics#172]
We should use `dmesg -T` as this will give us real timestamps instead of mills since startup. 
It's available on Ubuntu 14.04/16.04 and RHEL7, unfortunately not on RHEL6.
@nemonster is there a way to only use `-T` if it's a supported version? (Otherwise the command will fail)

**Comment by jpcarey** [comment]
duplicate to https://github.com/elastic/elasticsearch-support-diagnostics/issues/161 ?

**Comment by nemonster** [comment]
I don't think this is do-able until RHEL 6 goes out of support. There isn't really any easy way to do this, and there also appears to be some disagreement as to whether its necessary. I'd say see the issue referenced above for a stopgap.
