### ISSUE TITLE
Add collection of logstash logs when diag tool runs with logstash type option

### ISSUE THREAD

**Issue by e-mars** [elastic/elasticsearch-support-diagnostics#176]
Allow for collection of logstash logs when using the `--type logstash` to gather info from a logstash instance.
Maybe at least latest logs.

thx,
marcelo

**Comment by nemonster** [comment]
Sorry to say but given the current state of the Logstash API I can't do this consistently. With Elasticsearch, it provides the log location via the API. There's nothing in Logstash currently that shows this. Given the variety of ways to modify the location of logs it isn't trivial to determine where they are. I think the first start here would be a PR that requests this information get dumped out into via Logstash API along with things like JVM version, etc.
