### ISSUE TITLE
timestamp should match tar file name and path / extracted location

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch-support-diagnostics#179]
Very cosmetic issue. I usually reference the diagnostic by the last couple digits, but sometimes the tar file has a different time (usually off by 1) of the extracted folder.

![tar_name](https://user-images.githubusercontent.com/5118470/31747515-958a96ea-b42a-11e7-85c6-581dc4a5e6d6.png)

**Comment by nemonster** [comment]
Fixed next release. My bad on this one, no excuses.
