### ISSUE TITLE
Shard/Index  Cardinalities Are Zero'd Out When Indexes Are Closed

### ISSUE THREAD

**Issue by MorrieAtElastic** [elastic/elasticsearch-support-diagnostics#189]
When a cluster has many indexes which are closed, all shard & index cardinalities are displayed in the "Shard Assignment" page as having 0 documents and 0 shards. 

- the underlying data in the cat_indices.txt file shows index cardinalities and numbers of shard correctly for all open indexes. 

- I have 2 set of statistics from the same cluster generated by the customer 1 week apart and they show the same 0-documents and 0-shards for all indexes regardless of whether they are open or closed; I have compared that with the "Shard Assignment" numbers for another customer's cluster with no closed indexes and I have found no such problem in the "Shard Assignment" display for that cluster. 

- I have not tried to deterministically reproduce problem this by introducing a false set of index statistics. 

- I am not providing the statistics archives which reproduce the display problem at this time due to  customer confidentiality; I'm happy to provide them if confidentiality can be protected.

**Comment by jjfalling** [comment]
Issue opened in the wrong repo.
