### ISSUE TITLE
Argument --ptp doesn't work

### ISSUE THREAD

**Issue by jesuslinares** [elastic/elasticsearch-support-diagnostics#197]
Hi,

I want to run the diagnostics every 15 minutes, so I need to set the Elastic password as an argument in a script.

This command works:
`./diagnostics.sh --host hostname -s -u elastic -p`

But, if I use the argument ptp, it doesn't work:
`./diagnostics.sh --host hostname -s -u elastic --ptp password`

> Using /bin/java as Java Runtime
> Using -Xms256m -Xmx2000m  for options.
> 16:39:13 INFO  Validating inputs...
> 16:39:13 INFO  Creating temp directory.
> 16:39:13 INFO  Results will be written to: /home/diagnostics
> 16:39:13 INFO  Creating /home/diagnostics/diagnostics as temporary directory.
> 16:39:13 INFO  Created temp directory: /home/diagnostics/diagnostics
> 16:39:13 ERROR Testing
> 16:39:13 INFO  Configuring log file.
> 16:39:14 INFO  Writing diagnostic manifest.
> 16:39:14 INFO  Configuring REST endpoint.
> 16:39:14 INFO  Trying REST Endpoint.
> 16:39:14 WARN  https://...hostname...:9200/ query returned: 401/Unauthorized
> 16:39:14 ERROR Error writing response for null to disk.
> java.lang.RuntimeException: Authentication failure: invalid login credentials. 401/Unauthorized
>         at com.elastic.support.util.RestModule.checkResponseCode(RestModule.java:106) ~[support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.util.RestModule.submitRequest(RestModule.java:64) [support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.util.RestModule.submitRequest(RestModule.java:45) [support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.diagnostics.commands.VersionAndClusterNameCheckCmd.execute(VersionAndClusterNameCheckCmd.java:26) [support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:32) [support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:36) [support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.diagnostics.Diagnostic.exec(Diagnostic.java:97) [support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:15) [support-diagnostics-6.3.jar:6.3]
> 16:39:14 ERROR Error retrieving Elasticsearch version  - unable to continue..  Please make sure the proper connection parameters were specified
> java.lang.NullPointerException: null
>         at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:822) ~[jackson-core-2.5.3.jar:2.5.3]
>         at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578) ~[jackson-databind-2.5.3.jar:2.5.3]
>         at com.elastic.support.diagnostics.commands.VersionAndClusterNameCheckCmd.execute(VersionAndClusterNameCheckCmd.java:28) [support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:32) [support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:36) [support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.diagnostics.Diagnostic.exec(Diagnostic.java:97) [support-diagnostics-6.3.jar:6.3]
>         at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:15) [support-diagnostics-6.3.jar:6.3]
> 16:39:14 INFO  Archiving diagnostic results.
> 16:39:14 INFO  Archive: /home/diagnostics/diagnostics-20180221-163914.tar.gz was created
> 16:39:14 INFO  Temp directory /home/diagnostics/diagnostics was deleted.

The password contains letters, numbers, and symbols.

Is it a bug?.

Thanks.

**Comment by nemonster** [comment]
Not sure. I just tried the following:
--host localhost -u testuser -s --ptp t3st##m3

That's a combo of letters, numbers, and symbols for the password. It's working for me. The standard elastic/changeme worked as well.

Are you absolutely sure the ptp password you're sending in is correct? And you referenced using a script - is this running out of the script or have  you tried the same syntax on the command line?

**Comment by jesuslinares** [comment]
It was my bad. The password has the symbol "$", so the shell was evaluating it.

Thanks.
