### ISSUE TITLE
Implement log sanitization

### ISSUE THREAD

**Issue by nellicus** [elastic/elasticsearch-support-diagnostics#30]
need to replace with dummy data:

- IPs;
- ports;
- Hostnames;

any other info revealing sensitive information.
ideally some consistency should be kept to be able to correlate information during troubleshooting

e.g. 
real data
dedicated master srv23.secret.domain 10.37.12.32 HTTP 9200 Transport 9300
data node srv24.secret.domain 10.37.12.33 HTTP 9201 Transport 9301
data node srv25.secret.domain 10.37.12.34 HTTP 9202 Transport 9302

sanitised data
dedicated master dm.x.y x.x.x.32 HTTP 1 Transport 10
data node 1 -> dn.x.y x.x.x.33 HTTP 2 Transport 11
data node 2 -> dn.x.y x.x.x.x.34 HTTP 3 Transport 12

**Comment by damianpfister** [comment]
+1. Had a customer state that it would be very difficult to provide logs to us due to the sensitivity of data included therein. This feature would allow them to work around this quick easily.

**Comment by nemonster** [comment]
Done, in 2.0.6.  You just have to configure key: value pairs for the strings you want replaced and what to substitute.  Will work for logs and configuration.
