### ISSUE TITLE
AWS/Cloud provider key masking

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-support-diagnostics#39]
Related to https://github.com/elasticsearch/elasticsearch-support-diagnostics/issues/30 but higher priority.  Things like keys for aws can appear in yml and cluster state output.  Would be nice to mask them automatically before packaging.

**Comment by jjfalling** [comment]
I think this is now implemented in the aws plugin so it won't appear in the cluster state, but we still need it for the config.

**Comment by nemonster** [comment]
Right now I just copy the file - this implies that I'm reading the config file (or multiples if there are mulitple nodes deployed) and rewriting it before outputting the diagnostic.  As well as going through all the settings info in the nodes.json, right?

**Comment by jjfalling** [comment]
Yes, this would mean parsing the config files, but I think the plugins no longer put the creds in the cluster state. We need to verify this though.

**Comment by nemonster** [comment]
Done, in 2.0.6
