### ISSUE TITLE
Remove rmdir $outputdir line or need some additional checks to prevent accidental deletion of important directories

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-support-diagnostics#4]
While this (https://github.com/elasticsearch/elasticsearch-support-diagnostics/blob/master/bin/support-diagnostics.sh#L80) is a convenience feature (for removing the outputdir if host is not reachable), it is quite dangerous esp if the script is run with sudo or root privileges.  Had a scenario in the field where -H is specified but not reachable and the user happened to have -o set to the directory where ES is installed, as a result, that directory is removed and the ES installation is gone ...

```
#ensure we can connect to the host, or exit as there is nothing more we can do
connectionTest=`curl -s -S -XGET $eshost 2>&1`
if [ $? -ne 0 ]
then
    echo "Error connecting to $eshost: $connectionTest"
    rmdir $outputdir
    exit 1
fi
```

**Comment by jjfalling** [comment]
Should be fixed in the 2.x release. If not please reopen.
