### ISSUE TITLE
Diagnostics plugin should also pull segments API?

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch-support-diagnostics#55]
It would be helpful if we could see the segments API output when we pull diagnostics, e.g. this would let us see which Lucene version wrote which segments in each index.

```
    curl -XGET 'http://localhost:9200/_segments'
```

**Comment by jjfalling** [comment]
I thought this was already included in the recovery but it isn't. ++ to
adding it.

**Comment by jjfalling** [comment]
Look like this is already in 2.0.

**Comment by mikemccand** [comment]
Oh I see, that's great.  Can we back port it...?  Which version do users use?

**Comment by jjfalling** [comment]
In both the current version and the java rewrite. Closing this issue.
