### ISSUE TITLE
Capture kernel version

### ISSUE THREAD

**Issue by nellicus** [elastic/elasticsearch-support-diagnostics#63]
Linux
$ uname -a
Linux w530 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

OSX
$ uname -a
Darwin Antonios-MacBook-Air-2.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

Windows
http://www.windows-commandline.com/find-windows-os-version-from-command/ ?

**Comment by nellicus** [comment]
@jjfalling

**Comment by joshuar** [comment]
For just the kernel version, probably `uname -r` is enough on Linux.  Not sure if that parameter works the same on OSX?

**Comment by jjfalling** [comment]
Duplicate of https://github.com/elastic/elasticsearch-internal-support-tools/issues/55

**Comment by nemonster** [comment]
Given that this will only identify the the host where the diagnostic is being run, it would seem to limit the usefulness as a first pass diagnostic.  Although it's easy enough to add, at least for Linux.

**Comment by jjfalling** [comment]
I think the current version is sufficient. @joshuar @nellicus  thoughts?
