### ISSUE TITLE
Multiple runs - one file per run

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#68]
Some files are created at beginning of multiple runs (version.json) and others created for each run.
Could we have one file per run which in itself is complete?  This would make incremental processing easier as each diagnostic would be complete (and the unlikely event that one of the common files had changed between runs would be removed).

**Comment by jjfalling** [comment]
This should be fixed in the 2.x release of this utility. If not please reopen the issue.
