### ISSUE TITLE
Capture log files based on node configuration, not default location

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#70]
Currently logs are grabbed from the default location - sometimes these are old logs, or no logs at all...
Possible to learn the configured location of log files from the nodes settings and capture the correct log files?

**Comment by jjfalling** [comment]
This should be fixed in the 2.x release of this utility. If not please reopen the issue.

**Comment by sherry-ger** [comment]
On Windows, config file is included based on settings in the elasticsearch.yml file but not logs.

**Comment by nemonster** [comment]
No followup information-can't be reproduced.
