### ISSUE TITLE
Plugin does not install on ES 2.0

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-support-diagnostics#75]
There are 2 issues to address for ES 2.0 with the existing plugin:

1)  The installation step using `--install` no longer works in 2.0:

Change:

```
./bin/plugin --install elasticsearch/elasticsearch-support-diagnostics
```
To:

```
./bin/plugin install elasticsearch/elasticsearch-support-diagnostics
```

2)  Plugin does not install via the plugin command above because it is missing the now-required [plugin-descriptor.properties](https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html#_plugin_descriptor_file)

**Comment by jjfalling** [comment]
This should be fixed in the 2.x release of this utility. If not please reopen the issue.
