### ISSUE TITLE
Cannot install plugin on 1.5.0 version of ES

### ISSUE THREAD

**Issue by biggert** [elastic/elasticsearch-support-diagnostics#77]
Running the command recommend in the documentation `./bin/plugin --install elasticsearch/elasticsearch-support-diagnostics` fails with the following:

```
-> Installing elasticsearch/elasticsearch-support-diagnostics...
Trying https://github.com/elasticsearch/elasticsearch-support-diagnostics/archive/master.zip...
Failed to install elasticsearch/elasticsearch-support-diagnostics, reason: failed to download out of all possible locations..., use --verbose to get detailed information
````

Using `./bin/plugin --install elastic/elasticsearch-support-diagnostics` seems to work.

Side note, most of the links in the documentation in this repo all point to the old "elasticsearch/..." github repo instead of the new "elastic/..." so I'm assuming this bug an artifact of that as well.

**Comment by jjfalling** [comment]
This should be fixed in the 2.x release of this utility. If not please reopen the issue.
