### ISSUE TITLE
Need --ssl_verify false option

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#80]
For clusters with shield and self-signed certs, it is necessary to have an option to allow ssl, but disable ssl certificate verification.  This is particularly necessary for test/dev clusters where importing the CA is too much overhead.

**Comment by nemonster** [comment]
It already does.  It's not an option.  Otherwise everyone would have to configure the truststore for every JVM they were going to run it under.  It essentially acts the way a browser would if you go the message, "Do you want to go ahead anyway." and just submits the request.

**Comment by robin13** [comment]
Ah.... so if you try to connect it warns, but give's an option to continue?

**Comment by nemonster** [comment]
No, it just continues anyway.  The purpose of the message is to warn you that the site you are going to is potentially untrusted.  If you're an admin running a diagnostic against your own installed cluster are you really concerned with that site being untrusted?  Note that everything is still using SSL so it's not like the transmission is unprotected.

**Comment by robin13** [comment]
Ok - thank you!

**Comment by robin13** [comment]
Re-opening because it seems there are times when this does not work...

**Comment by nemonster** [comment]
Done, in 2.0.6.  Although it still seems like the wrong thing to do.
