### ISSUE TITLE
Don't collect top / logs / config if not a cluster host

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#82]
Often we have diagnostics from customers where the diagnostics has been run on a machine which has a development Elasticsearch installation, but is not a node in the cluster.  In this case it is very confusing and misleading to have the top / config / logs in the diagnostics, because they usually have nothing to do with the cluster.
Would it be possible to identify if the diagnostics is being executed on a cluster node machine, and only collect these machine sections if it is a cluster node machine?
It would also be good to have some warning output noting that the config / logs have not been collected if the diagnostics was run from an external machine, or they could not be found / read.

**Comment by nemonster** [comment]
The REST based statistics are retrieved prior to any log processing.  And you need the output from the _nodes command to find the location of the logs and config, as well as seeing whether or not at least one of the nodes IP or hostname matches that of the host where the script is being executed. 

Would it be acceptable to do a check after the information is collected and write an entry to the manifest indicating if the host the script is being run from doesn't match a host in the collected list?  Could also disregard checking for logs and configs if this was the case as well.

**Comment by robin13** [comment]
I would prefer each diagnostic being as clear as possible (i.e. diagnostics from one node only), so noting incompleteness in the metadata would be a patch IMO, but collecting only relevant data would be the solution.

**Comment by nemonster** [comment]
Now has a remote option to run specifically as a just a call to the REST interface.

**Comment by robin13** [comment]
This `--type remote` option is something which needs to be actively done by the user, and the default value is `standard` which collects top information: I have not seen any example yet of someone using the `remote` option, but many examples of diagnostics created from a remote machine thereby capturing invalid top / logs / configuration / uname.
Would in not be possible to have it automatic unless overridden with an explicit `--type` call?
