### ISSUE TITLE
Logfile with full timestamps

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#83]
The log files created have the date in the filename and the timestamp in the file - that makes it very difficult to process...
Would it be possible to have a full ISO8601 timestamp in the log file?

**Comment by robin13** [comment]
See #84

**Comment by nemonster** [comment]
Don't quite understand this. Other than the archive I don't have any files with dates in them.

**Comment by robin13** [comment]
Sample from the logs:

```
12:08:38.238 [main] ERROR c.e.s.d.RestModule - Error submitting request
:
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
```
