### ISSUE TITLE
ISO8601 timestamps everywhere

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#84]
Would it be possible to have a full ISO8601 timestamp everywhere a timestamp is written? :)

![iso8601-all-the-timesamps](https://cloud.githubusercontent.com/assets/174291/12671156/0c5fcfc6-c66e-11e5-8e0d-8baea6794253.jpg)

**Comment by nemonster** [comment]
Will be in the 2.0.3 release.

**Comment by robin13** [comment]
Is not... :(

Diagnostics file created:

```
diagnostics-02-09-2016 04:04:35 PM +0100.tar.gz
```
