### ISSUE TITLE
shards.json is not valid json

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#86]
This does not come from an API endpoint directly does it?
It is not valid json, and so cannot be processed:

```
[{"index":"pingboard","shard":"0","prirep":"p","state":"STARTED","docs":"284","store":"1.3mb","ip":"172.17.0.157","node":"instance-0000000008"},{"index":"github_webhook","shard":"0","prirep":"p","state":"STARTED","docs":"3","store":"3kb","ip":"172.17.0.157","node":"instance-0000000008"},
...
```

**Comment by nemonster** [comment]
_cat/shards?format=json

If you look in diags.yml, you'll see it there.  Everything in comes from an endpoint except the manifest.

> It is not valid json, and so cannot be processed:

Well, Jackson takes it just fine.  And if you plug it into [Json Lint](http://jsonlint.com) I see:

```
Results

Valid JSON
```
So you may also want to specify the criteria by which you are determining that it is not valid.

**Comment by robin13** [comment]
Sorry... my bad... have found problem with the JSON parsing module I was using.
