### ISSUE TITLE
Diagnostics filename should be safe

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#87]
Current filename created looks e.g. like this:

```
diagnostics-02-09-2016 04:04:35 PM +0100.tar.gz
```
or this
```
diagnostics-02-09-2016 03/56/20 PM +0100.tar.gz
```

Depending where it was created (locale?)...  The filename created should be safe for all environments: characters which should not be used: `+ / : ` ... others?

**Comment by robin13** [comment]
suggest strftime format:  `support-diagnostics-%Y%m%d%H%M%S.tar.gz`

**Comment by jakommo** [comment]
:+1:

**Comment by GlenRSmith** [comment]
:+1:

**Comment by jjfalling** [comment]
++ I think a reliable time and date stamp with offset should be in a metadata doc inside the dump, not in the filename where someone can screw with it

**Comment by robin13** [comment]
Or even more simple, just `elasticsearch-support-diagnostics.tar.gz`.  If it needs renaming to be uploaded / avoid clashes that can be done manually.

To quote a great thinker: 

> If you're relying on a timestamp in the filename for /anything/, you're doing it wrong

**Comment by GlenRSmith** [comment]
:+1: to @robin13 's further simplification.

**Comment by nemonster** [comment]
it's not in the filename for any other reason than to make it easier to prevent a collision if a new one is generated.
